name: "@ankogit"
url: https://ankogit.github.io
description: I`m learn and teach

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']




